config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  post '/login', to: 'sessions#create'
  resources :posts, only: %i[new create index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

# Application Record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

# Post
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
# frozen_string_literal: true

# User
class User < ApplicationRecord
  before_create :remember
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :posts

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def authenticated?(remember_token)
    BCrypt::Password.new(:remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def self.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def remember
    self.remember_token = User.new_token
    self.remember_digest = User.encrypt(remember_token)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application Controller
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  helper_method :logged_in?

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    remember_token = User.new_token
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
    user.update_attribute(:remember_digest, User.encrypt(remember_token))
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

  private

  def logged_in_user
    flash[:danger] = 'Please log in' unless logged_in?
    redirect_to login_path unless logged_in?
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# Posts Controller
class PostsController < ApplicationController
  before_action :logged_in_user, only: %i[new create]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = 'Post was successfully created'
      redirect_to posts_path
    else
      flash.now[:danger] = 'Post could not be created'
      render 'new'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# sessions controller
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in user
      remember user
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Users Controller
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:info] = 'Welcome!'
      redirect_to root_url
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Application Helper
module ApplicationHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

# Posts Helper
module PostsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

# Sessions Helper
module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# Users Helper
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
    <%= link_to 'Logout', logout_path %>
    <% else %>
    <%= link_to 'Login ', login_path%>
    <%= link_to '/ Signup', signup_path%>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>
<% if logged_in? %>
  <%= link_to 'New post', new_post_path %><br>
<% end %>

<% @posts.each do |post| %>
  <% if logged_in? %>
    <p><%= post.user.name %></p>
    <% else %>
    <%= link_to 'Log in to see author', login_path %>
  <% end %>
  <h3><%= post.title%></h3><br>
  <p><%= post.body%><p>
<% end %>

app/views/posts/new.html.erb
<h1>Add Post</h1>
<%= form_for(:post, url: posts_path) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user, url: signup_path) do |f| %>

<%= f.label :name %><br>
<%= f.text_field :name %><br>

<%= f.label :email %><br>
<%= f.email_field :email %><br>

<%= f.label :password %><br>
<%= f.password_field :password %><br>

<%= f.label :password_confirmation, "Confirmation" %><br>
<%= f.password_field :password_confirmation %><br>

<%= f.submit "Create my account" %>
<% end %>